### ISSUE TITLE
Cannot add taskc tasks

### ISSUE THREAD

**Issue by TomJohnZ** [CCExtractor/taskwarrior-flutter#490]
### Describe your issue

After enabling `Taskchampion sync`, I am unable to create new tasks.

Current debug build: 1fe609a

### Steps to reproduce

1. Do a fresh `--debug` APK install
2. Change `Taskchampion sync` to true
3. Press "+" button and enter a task description
4. Click "Save"
5. `Task Added Successfully!` snackbar appears, but no task has been created

### What was the expected result?

A task to be visible on the home page

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [x] I have starred the repo ⭐ and watched 👀 it on GitHub and followed the contribution guidelines.

**Comment by notklea** [comment]
Could this be closed since it was fixed, as per [comment](https://github.com/CCExtractor/taskwarrior-flutter/issues/491#issuecomment-3002348796)?

**Comment by TomJohnZ** [comment]
Unfortunately, this bug still seems to be present. I just tested it on commit 9cd58b3, and the same issue remains.

The [comment](https://github.com/CCExtractor/taskwarrior-flutter/issues/491#issuecomment-3002348796) was regarding to the other (unrelated) [bug fix](https://github.com/CCExtractor/taskwarrior-flutter/issues/491), but this one still seems to be present.

**Comment by SGI-CAPP-AT2** [comment]
> Unable to reproduce ,Steps to reproduce are **incomplete** please provide details like what are your settings and please see if your fork is synced and repo clone is up to date If yes please acknowledge

@parthakadam2007, this is problem with ccsync server for sync
The pre-sync (tasks without uuids) are not being displayed.

@TomJohnZ , @notklea You can use taskchampion server for the profile to fix this instead of using ccsync. The credentials of ccsync will be valid for this as well.
